import platform

sys = platform.system()

env = Environment()

if sys == "Darwin":
    env.Append(LINKFLAGS = ' -framework OpenGL -framework GLUT')
else:
    env.Append(LINKFLAGS = '-lGL -lGLU -lglut')
    
env.Program(source = ['Braitenberg Vehicle.cpp', 'Point.cpp', 'Vehicle.cpp', 'Velocity.cpp'], target = 'BraitenbergVehicle.out')

